### ISSUE TITLE
Cannot log in to any of the localhost

### ISSUE THREAD

**Issue by feistycatkik** [archivesspace/tech-docs#164]
Hi all, I am in dire need of help with a problem that I've encountered: I am almost done with all the steps provided on the [documentation page](https://archivesspace.github.io/tech-docs/administration/getting_started.html)  but I can't seem to connect to any of the localhost URL 

I made sure everything was running (solr/sql), made neccessary modifications during launch and the ArchivesSapceService shows that it's started. I even went to through Service of Control Panel to confirm this and it did. but it is not letting me connect to the localhost. I have tried everything: disabling firewalls, adding to the Windows defender all the ports archivesspace will be uses, disabling chrome proxy settings, switching to Microsoft Edge rebooting the system everytime these changes are made but none worked.  Have anyone encountered similar issues when installing archivesspace? Have I skipped any crucial step that may lead to this?  

I am operating on a Windows 11 with a Solr 8 and Archivesspace 3.4 running against Mysql 8.0 and Java 1.80 and the latest connecter (1.8.30) 

Thank you!

**Comment by feistycatkik** [comment]
**i just tried logging onto the localhost again and this is what is got:**

_

> Connection refused - Failed to open TCP connection to localhost:8983 (Connection refused - connect(2) for "localhost" port 8983) from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:943:in `block in connect' from org/jruby/ext/timeout/Timeout.java:114:in `timeout' from org/jruby/ext/timeout/Timeout.java:90:in `timeout' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:939:in `connect' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:924:in `do_start' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:913:in `start' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:609:in `start' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:485:in `get_response' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/model/solr.rb:28:in `lookup_external_checksum' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/model/solr.rb:17:in `external_checksum' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/model/solr.rb:13:in `checksum_valid?' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/model/solr.rb:94:in `verify_checksum!' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/model/solr.rb:89:in `verify_checksums!' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/main.rb:152:in `block in ArchivesSpaceService' from C:/archivesspace/gems/gems/sinatra-2.2.4/lib/sinatra/base.rb:1486:in `configure' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/main.rb:99:in `<class:ArchivesSpaceService>' from C:/archivesspace/data/tmp/jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427/webapp/WEB-INF/app/main.rb:46:in `<main>' from org/jruby/RubyKernel.java:974:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83:in `require' from C:\archivesspace\data\tmp\jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427\webapp\WEB-INF\config.ru:4:in `block in <main>' from org/jruby/RubyBasicObject.java:2622:in `instance_eval' from uri:classloader:/vendor/rack-2.2.3/rack/builder.rb:125:in `initialize' from C:\archivesspace\data\tmp\jetty-0_0_0_0-8089-backend_war-_-any-9093080962870081427\webapp\WEB-INF\config.ru:1:in `<main>' from C:\archivesspace\launcher\launcher.rb:90:in `start_server' from C:\archivesspace\launcher\launcher.rb:144:in `main' from C:\archivesspace\launcher\launcher.rb:242:in `<main>'
> 
> You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

_
